---
- name: Install Vim
  become: true
  tags: vim
  block:
    - name: Install
      apt:
        name: vim
        update_cache: true

    - name: Set as the default editor
      alternatives:
        name: editor
        path: /usr/bin/vim.basic
